FROM php:8.3-alpine

RUN apk add --no-cache git curl zip unzip sqlite sqlite-dev bash

RUN docker-php-ext-install pdo pdo_sqlite bcmath

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

# Copia a pasta src (o laravel) para dentro do container
COPY src/ /var/www/

# Instala as dependências
RUN composer install --no-dev --optimize-autoloader --no-interaction

# Permissão no entrypoint
RUN chmod +x /var/www/entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["/var/www/entrypoint.sh"]
